/* eslint-disable @next/next/no-img-element, react/no-unescaped-entities */
// Source illustrations retain their registered dimensions and transparent layers.
import type { ManasMessages } from "./translations";

export default function ManasContent({ messages: t }: { messages: ManasMessages }) {
    return <>

    <a className="skip" href="#main">{t.s001}</a>
    <svg xmlns="http://www.w3.org/2000/svg" width="0" height="0" aria-hidden="true" style={{ "position": "absolute", "overflow": "hidden" }}><defs>

    <mask id="supplied-emblem-mask" maskUnits="userSpaceOnUse" x="0" y="0" width="100" height="100" style={{ "maskType": "luminance" }}><image href="/manas/emblem.jpg" x="-19.688889" y="-19.688889" width="140" height="140"/></mask>
    <mask id="emblem-rays-mask" maskUnits="userSpaceOnUse" x="0" y="0" width="140" height="140" style={{ "maskType": "luminance" }}><rect width="140" height="140" fill="white"/><circle cx="70" cy="70" r="42.1" fill="black"/></mask>
    <clipPath id="emblem-center-clip"><circle cx="70" cy="70" r="42.5"/></clipPath>
    <symbol id="tunduk" viewBox="0 0 100 100"><rect width="100" height="100" fill="currentColor" mask="url(#supplied-emblem-mask)"/></symbol>
    <symbol id="horn" viewBox="0 0 100 80"><g fill="none" stroke="currentColor" strokeWidth="7" strokeLinecap="square" strokeLinejoin="round"><path d="M50 72V43C50 28 34 14 22 14S5 23 8 33s19 12 20 1c0-7-9-8-10-2M50 72V43c0-15 16-29 28-29s17 9 14 19-19 12-20 1c0-7 9-8 10-2M33 67l17-17 17 17"/></g></symbol>
    <symbol id="kerege" viewBox="0 0 100 100"><g fill="none" stroke="currentColor" strokeWidth="3"><path d="M50 5L95 50 50 95 5 50ZM50 20L80 50 50 80 20 50ZM50 36L64 50 50 64 36 50Z"/><path d="M27 27l46 46M27 73l46-46"/></g></symbol>
    <symbol id="tumar" viewBox="0 0 100 100"><g fill="none" stroke="currentColor" strokeWidth="3"><path d="M50 11L89 77H11ZM50 29L72 67H28ZM24 78v14m13-14v18m13-18v14m13-14v18m13-18v14"/><circle cx="50" cy="53" r="5"/></g></symbol>
    <symbol id="warrior" viewBox="0 0 100 110"><g fill="none" stroke="currentColor" strokeWidth="2"><path d="M50 6v14M23 47q5-24 27-32 22 8 27 32M19 48h62M29 49v27l21 13 21-13V49M38 59h6m12 0h6M47 61l-3 12h12M38 77q12 8 24 0M25 78L13 92v13h74V92L75 78M34 85l16 15 16-15M30 33q20 14 40 0"/><path d="M20 94l8 10m0-13 12 13m20 0 12-13m0 13 8-10"/></g></symbol>
    <symbol id="shyrdak" viewBox="0 0 240 60"><g fill="none" stroke="currentColor" strokeWidth="3"><path d="M0 30h25l20-20 20 20-20 20-20-20M75 30h20l25-25 25 25-25 25-25-25h50M165 30h10l20-20 20 20-20 20-20-20h65"/><path d="M108 30q-16-23-21-9-3 10 8 5m37 4q16-23 21-9 3 10-8 5M109 32q-16 23-21 9-3-10 8-5m36-4q16 23 21 9 3-10-8-5"/></g></symbol>
    </defs></svg>

    <div id="main">
    <section className="hero" aria-labelledby="hero-title">
    <div className="hero-stage">
    <div className="hero-art" role="img" aria-label={t.s002}>
  <div className="hero-layer hero-landscape" data-depth="0.18"><img src="/manas/hero-background.webp" width="1983" height="793" alt=""/></div>
  <div className="hero-layer hero-army" data-depth="0.08"><img src="/manas/hero-army.webp" width="1983" height="793" alt=""/></div>
  <div className="hero-layer hero-manas" data-depth="-0.045"><img src="/manas/hero-manas.webp" width="1983" height="793" alt=""/></div>
    </div>
    <div className="container hero-content"><div className="eyebrow hero-kicker"><span className="little-diamond"></span>{" "}{t.s003}</div><h1 id="hero-title" lang="ky">МАНАС</h1><div className="latin-title">{t.s004}</div><p className="hero-subtitle">{t.s005}</p><p className="hero-kyrgyz" lang="ky">Кыргыз баатырынын дастаны</p><p className="hero-copy">{t.s006}<br />{t.s007}<br />{t.s008}</p><a className="primary-link" href="#origin">{t.s009}{" "}<span className="arrow" aria-hidden="true">↗</span></a></div>
    <div className="hero-quote"><blockquote lang="ky">“Көкжал дөбөт бөрү эле”</blockquote><p>{t.s012}</p></div>
    </div>
    </section>
    <div className="heritage-strip"><div className="container heritage-inner"><div className="heritage-item"><span className="stat-number">40</span><span className="stat-label">{t.s013}<br />{t.s014}</span></div><div className="heritage-item"><span className="stat-number">3</span><span className="stat-label">{t.s015}<br />{t.s016}</span></div><div className="heritage-item"><svg width="34" height="34" className="red" aria-hidden="true"><use href="#tunduk"/></svg><span className="stat-label">{t.s017}<br />{t.s018}</span></div><a className="heritage-note" href="https://ich.unesco.org/en/RL/kyrgyz-epic-trilogy-manas-semetey-seytek-00876" target="_blank" rel="noopener noreferrer"><svg aria-hidden="true"><use href="#kerege"/></svg><span>{t.s019}<br />{t.s020}{" "}<span aria-hidden="true">↗</span></span></a></div></div>
    <section className="chapter" id="origin" aria-labelledby="origin-title"><div className="container origin-layout"><div className="reveal"><div className="chapter-top"><span className="chapter-number">01</span><span className="rule"></span><span className="eyebrow">{t.s021}</span></div><h2 id="origin-title">{t.s022}<br />{t.s023}{" "}<em>{t.s024}</em></h2><p className="kyrgyz-title" lang="ky">Жаралуу</p><div className="prose"><p>{t.s025}</p><p>{t.s026}</p></div><a className="text-link" href="#comrades">{t.s027}{" "}<span aria-hidden="true">↗</span></a></div><figure className="origin-art reveal" style={{ "margin": "0" }}><div className="art-frame"><img className="origin-image" src="/manas/origin.jpg" width="1536" height="1024" alt={t.s028} loading="lazy" decoding="async"/></div><figcaption className="art-caption"><span>{t.s029}</span><span>{t.s030}</span></figcaption></figure></div></section>
    <div className="ornament-divider" aria-hidden="true"><svg><use href="#shyrdak"/></svg></div>
    <section className="chapter" id="comrades" aria-labelledby="comrades-title"><div className="container"><div className="section-heading reveal"><div><div className="chapter-top"><span className="chapter-number">02</span><span className="rule"></span><span className="eyebrow">{t.s031}</span></div><h2 id="comrades-title">{t.s032}<br /><em>{t.s033}</em></h2></div><div><p className="kyrgyz-title" lang="ky">Кырк Чоро</p><p className="section-intro">{t.s034}</p></div></div>
    <div className="comrade-gallery reveal" aria-label={t.s035}>
    <button className="comrade-card" data-person="almambet" aria-haspopup="dialog"><span className="card-top"><span>{t.s036}</span><svg width="23" height="23" aria-hidden="true"><use href="#horn"/></svg></span><span className="card-portrait"><img src="/manas/almambet.webp" width="1122" height="1402" alt={t.s037} loading="lazy" decoding="async"/></span><span className="card-content"><span className="card-details"><span className="card-name">{t.s038}</span><span className="card-role">{t.s039}</span></span><span className="card-arrow" aria-hidden="true">↗</span></span></button>
    <button className="comrade-card" data-person="chubak" aria-haspopup="dialog"><span className="card-top"><span>{t.s040}</span><svg width="23" height="23" aria-hidden="true"><use href="#horn"/></svg></span><span className="card-portrait"><img src="/manas/chubak.webp" width="1122" height="1402" alt={t.s041} loading="lazy" decoding="async"/></span><span className="card-content"><span className="card-details"><span className="card-name">{t.s042}</span><span className="card-role">{t.s043}</span></span><span className="card-arrow" aria-hidden="true">↗</span></span></button>
    <button className="comrade-card" data-person="syrgak" aria-haspopup="dialog"><span className="card-top"><span>{t.s044}</span><svg width="23" height="23" aria-hidden="true"><use href="#horn"/></svg></span><span className="card-portrait"><img src="/manas/syrgak.webp" width="1122" height="1402" alt={t.s045} loading="lazy" decoding="async"/></span><span className="card-content"><span className="card-details"><span className="card-name">{t.s046}</span><span className="card-role">{t.s047}</span></span><span className="card-arrow" aria-hidden="true">↗</span></span></button>
    <button className="comrade-card" data-person="bakai" aria-haspopup="dialog"><span className="card-top"><span>{t.s048}</span><svg width="23" height="23" aria-hidden="true"><use href="#tunduk"/></svg></span><span className="card-portrait"><img src="/manas/bakai.webp" width="1122" height="1402" alt={t.s049} loading="lazy" decoding="async"/></span><span className="card-content"><span className="card-details"><span className="card-name">{t.s050}</span><span className="card-role">{t.s051}</span></span><span className="card-arrow" aria-hidden="true">↗</span></span></button>
    </div><div className="forty-label"><span>{t.s052}</span><span>{t.s053}</span></div><div className="forty-badges" aria-label={t.s054}></div><p className="gallery-note">{t.s055}</p><noscript><p className="no-js-note">{t.s056}</p></noscript></div></section>
    <section className="chapter battle" id="battles" aria-labelledby="battles-title"><div className="container"><div className="section-heading reveal"><div><div className="chapter-top"><span className="chapter-number">03</span><span className="rule"></span><span className="eyebrow">{t.s057}</span></div><h2 id="battles-title">{t.s058}<br /><em>{t.s059}</em></h2></div><div><p className="kyrgyz-title" lang="ky">Согуштар</p><p className="section-intro">{t.s060}</p></div></div><div className="battle-panels reveal"><div className="battle-main"><img src="/manas/manas-hero.jpg" width="1983" height="793" alt={t.s061} loading="lazy" decoding="async"/><div className="panel-caption">{t.s062}<br />{t.s063}</div></div><article className="battle-note kanykey-panel"><img className="kanykey-portrait" src="/manas/kanykey.webp" width="1122" height="1402" alt={t.s064} loading="lazy" decoding="async"/><div className="kanykey-copy"><svg aria-hidden="true"><use href="#tumar"/></svg><span className="eyebrow">{t.s065}</span><h3 style={{ "marginTop": "15px" }}>{t.s066}<br />{t.s067}</h3><p>{t.s068}</p><p>{t.s069}</p></div></article></div><div className="battle-footer"><p>{t.s070}</p><span lang="ky">Биримдик — элдин күчү.</span></div></div></section>

    <section className="chapter comic-episode" id="episode" aria-labelledby="episode-title">
 <div className="container">
  <div className="section-heading reveal">
   <div><div className="chapter-top"><span className="chapter-number">04</span><span className="rule"></span><span className="eyebrow">{t.s071}</span></div><h2 id="episode-title">{t.s072}<br /><em>{t.s073}</em></h2></div>
   <div><p className="kyrgyz-title" lang="ky">Көкөтөйдүн ашы</p><p className="section-intro">{t.s074}</p></div>
  </div>
  <p className="comic-reading-hint">{t.s075}</p><div className="comic-page" aria-label={t.s076}>
   <figure className="comic-panel comic-panel--feast reveal"><img src="/manas/comic-feast.webp" width="1600" height="800" alt={t.s077} loading="lazy" decoding="async"/><span className="comic-panel-number" aria-hidden="true">01</span><figcaption id="comic-caption-0"><strong>{t.s078}</strong>{" "}{t.s079}</figcaption><button type="button" className="comic-expand" data-comic="0" aria-label={t.s080} aria-describedby="comic-caption-0" aria-haspopup="dialog" aria-controls="comic-dialog"><span>{t.s081}{" "}<span aria-hidden="true">↗</span></span></button></figure>
   <figure className="comic-panel comic-panel--challenge reveal"><img src="/manas/comic-challenge.webp" width="1200" height="900" alt={t.s082} loading="lazy" decoding="async"/><span className="comic-panel-number" aria-hidden="true">02</span><figcaption id="comic-caption-1"><strong>{t.s083}</strong>{" "}{t.s084}</figcaption><button type="button" className="comic-expand" data-comic="1" aria-label={t.s085} aria-describedby="comic-caption-1" aria-haspopup="dialog" aria-controls="comic-dialog"><span>{t.s081}{" "}<span aria-hidden="true">↗</span></span></button></figure>
   <figure className="comic-panel comic-panel--clash reveal"><img src="/manas/comic-clash.webp" width="1600" height="800" alt={t.s086} loading="lazy" decoding="async"/><span className="comic-panel-number" aria-hidden="true">03</span><span className="comic-impact" aria-hidden="true">{t.s087}</span><figcaption id="comic-caption-2"><strong>{t.s088}</strong>{" "}{t.s089}</figcaption><button type="button" className="comic-expand" data-comic="2" aria-label={t.s090} aria-describedby="comic-caption-2" aria-haspopup="dialog" aria-controls="comic-dialog"><span>{t.s081}{" "}<span aria-hidden="true">↗</span></span></button></figure>
   <figure className="comic-panel comic-panel--aftermath reveal"><img src="/manas/comic-aftermath.webp" width="1200" height="900" alt={t.s091} loading="lazy" decoding="async"/><span className="comic-panel-number" aria-hidden="true">04</span><figcaption id="comic-caption-3"><strong>{t.s092}</strong>{" "}{t.s093}</figcaption><button type="button" className="comic-expand" data-comic="3" aria-label={t.s094} aria-describedby="comic-caption-3" aria-haspopup="dialog" aria-controls="comic-dialog"><span>{t.s081}{" "}<span aria-hidden="true">↗</span></span></button></figure>
  </div>
  <details className="episode-background"><summary>{t.s095}{" "}<span aria-hidden="true">+</span></summary><div className="episode-background-grid"><div><h3>{t.s096}</h3><p>{t.s097}</p></div><div><h3>{t.s098}</h3><p>{t.s099}</p></div><div><h3>{t.s100}</h3><p>{t.s101}</p></div></div></details><div className="comic-footnote"><p>{t.s102}</p><a href="https://slaviccenter.osu.edu/news/daniel-prior-visits-osu-reading-memorial-feast-kokotoy-khan" target="_blank" rel="noopener noreferrer">{t.s103}</a></div>
  <a className="text-link" href="#koshoy">{t.s104}{" "}<span aria-hidden="true">↗</span></a>
 </div>
    </section>

    <div className="comic-interlude" aria-hidden="true"><span>{t.s105}</span><svg viewBox="0 0 100 80"><use href="#horn"/></svg><span>{t.s106}</span></div>
    <section className="chapter comic-episode comic-episode--koshoy" id="koshoy" aria-labelledby="koshoy-title">
 <div className="container">
  <div className="section-heading reveal">
   <div><div className="chapter-top"><span className="chapter-number">05</span><span className="rule"></span><span className="eyebrow">{t.s107}</span></div><h2 id="koshoy-title">{t.s108}<br /><em>{t.s109}</em></h2></div>
   <div><p className="kyrgyz-title" lang="ky">Кошой менен Жолойдун күрөшү</p><p className="section-intro">{t.s110}</p></div>
  </div>
  <p className="comic-reading-hint">{t.s111}</p>
  <div className="comic-page" aria-label={t.s112}>
    <figure className="comic-panel comic-panel--challenge reveal"><img src="/manas/koshoy-challenge.webp" width="1200" height="900" alt={t.s113} loading="lazy" decoding="async"/><span className="comic-panel-number" aria-hidden="true">01</span><figcaption id="koshoy-caption-0"><strong>{t.s114}</strong>{" "}{t.s115}</figcaption><button type="button" className="comic-expand" data-episode="koshoy" data-comic="0" aria-label={t.s116} aria-describedby="koshoy-caption-0" aria-haspopup="dialog" aria-controls="comic-dialog"><span>{t.s081}{" "}<span aria-hidden="true">↗</span></span></button></figure>
    <figure className="comic-panel comic-panel--kandagai reveal"><img src="/manas/koshoy-kandagai.webp" width="1200" height="900" alt={t.s117} loading="lazy" decoding="async"/><span className="comic-panel-number" aria-hidden="true">02</span><figcaption id="koshoy-caption-1"><strong>{t.s118}</strong>{" "}{t.s119}</figcaption><button type="button" className="comic-expand" data-episode="koshoy" data-comic="1" aria-label={t.s120} aria-describedby="koshoy-caption-1" aria-haspopup="dialog" aria-controls="comic-dialog"><span>{t.s081}{" "}<span aria-hidden="true">↗</span></span></button></figure>
    <figure className="comic-panel comic-panel--blessing reveal"><img src="/manas/koshoy-blessing.webp" width="1200" height="900" alt={t.s121} loading="lazy" decoding="async"/><span className="comic-panel-number" aria-hidden="true">03</span><figcaption id="koshoy-caption-2"><strong>{t.s122}</strong>{" "}{t.s123}</figcaption><button type="button" className="comic-expand" data-episode="koshoy" data-comic="2" aria-label={t.s124} aria-describedby="koshoy-caption-2" aria-haspopup="dialog" aria-controls="comic-dialog"><span>{t.s081}{" "}<span aria-hidden="true">↗</span></span></button></figure>
    <figure className="comic-panel comic-panel--victory reveal"><img src="/manas/koshoy-victory.webp" width="1200" height="600" alt={t.s125} loading="lazy" decoding="async"/><span className="comic-panel-number" aria-hidden="true">04</span><span className="comic-impact" aria-hidden="true">{t.s126}</span><figcaption id="koshoy-caption-3"><strong>{t.s127}</strong>{" "}{t.s128}</figcaption><button type="button" className="comic-expand" data-episode="koshoy" data-comic="3" aria-label={t.s129} aria-describedby="koshoy-caption-3" aria-haspopup="dialog" aria-controls="comic-dialog"><span>{t.s081}{" "}<span aria-hidden="true">↗</span></span></button></figure>
  </div>
  <details className="episode-background"><summary>{t.s130}{" "}<span aria-hidden="true">+</span></summary><div className="episode-background-grid"><div><h3>{t.s131}</h3><p>{t.s132}</p></div><div><h3>{t.s133}</h3><p>{t.s134}</p></div><div><h3>{t.s100}</h3><p>{t.s135}</p></div></div></details>
  <div className="comic-footnote"><p>{t.s136}</p><div><a href="https://open.kg/en/about-kyrgyzstan/culture/folklore/kyrgyz-heroic-epic-manas/the-epic-manas-in-prose/35754-skazanie-o-manase-pominki-po-kekekteyu-chast-4.html" target="_blank" rel="noopener noreferrer">{t.s137}</a><br /><a href="https://open.kg/en/about-kyrgyzstan/culture/folklore/kyrgyz-heroic-epic-manas/the-epic-manas-in-prose/35780-skazanie-o-manase-pominki-po-kekekteyu-chast-5.html" target="_blank" rel="noopener noreferrer">{t.s138}</a></div></div>
  <a className="text-link" href="#flight">{t.s139}{" "}<span aria-hidden="true">↗</span></a>
 </div>
    </section>

    <div className="comic-interlude" aria-hidden="true"><span>{t.s140}</span><svg viewBox="0 0 100 100"><use href="#tumar"/></svg><span>{t.s141}</span></div>
    <section className="chapter comic-episode comic-episode--flight" id="flight" aria-labelledby="flight-title">
 <div className="container">
  <div className="section-heading reveal">
   <div><div className="chapter-top"><span className="chapter-number">06</span><span className="rule"></span><span className="eyebrow">{t.s142}</span></div><h2 id="flight-title">{t.s143}<br /><em>{t.s144}</em></h2></div>
   <div><p className="kyrgyz-title" lang="ky">Каныкейдин Букарга качышы</p><p className="section-intro">{t.s145}</p></div>
  </div>
  <p className="comic-reading-hint">{t.s146}</p>
  <div className="comic-page" aria-label={t.s147}>
    <figure className="comic-panel comic-panel--departure reveal"><img src="/manas/flight-departure.webp" width="1200" height="900" alt={t.s148} loading="lazy" decoding="async"/><span className="comic-panel-number" aria-hidden="true">01</span><figcaption id="flight-caption-0"><strong>{t.s149}</strong>{" "}{t.s150}</figcaption><button type="button" className="comic-expand" data-episode="flight" data-comic="0" aria-label={t.s151} aria-describedby="flight-caption-0" aria-haspopup="dialog" aria-controls="comic-dialog"><span>{t.s081}{" "}<span aria-hidden="true">↗</span></span></button></figure>
    <figure className="comic-panel comic-panel--crossing reveal"><img src="/manas/flight-crossing.webp" width="1200" height="600" alt={t.s152} loading="lazy" decoding="async"/><span className="comic-panel-number" aria-hidden="true">02</span><figcaption id="flight-caption-1"><strong>{t.s153}</strong>{" "}{t.s154}</figcaption><button type="button" className="comic-expand" data-episode="flight" data-comic="1" aria-label={t.s155} aria-describedby="flight-caption-1" aria-haspopup="dialog" aria-controls="comic-dialog"><span>{t.s081}{" "}<span aria-hidden="true">↗</span></span></button></figure>
    <figure className="comic-panel comic-panel--guardian reveal"><img src="/manas/flight-guardian.webp" width="1200" height="900" alt={t.s156} loading="lazy" decoding="async"/><span className="comic-panel-number" aria-hidden="true">03</span><figcaption id="flight-caption-2"><strong>{t.s157}</strong>{" "}{t.s158}</figcaption><button type="button" className="comic-expand" data-episode="flight" data-comic="2" aria-label={t.s159} aria-describedby="flight-caption-2" aria-haspopup="dialog" aria-controls="comic-dialog"><span>{t.s081}{" "}<span aria-hidden="true">↗</span></span></button></figure>
    <figure className="comic-panel comic-panel--reunion reveal"><img src="/manas/flight-reunion.webp" width="1200" height="900" alt={t.s160} loading="lazy" decoding="async"/><span className="comic-panel-number" aria-hidden="true">04</span><figcaption id="flight-caption-3"><strong>{t.s161}</strong>{" "}{t.s162}</figcaption><button type="button" className="comic-expand" data-episode="flight" data-comic="3" aria-label={t.s163} aria-describedby="flight-caption-3" aria-haspopup="dialog" aria-controls="comic-dialog"><span>{t.s081}{" "}<span aria-hidden="true">↗</span></span></button></figure>
  </div>
  <details className="episode-background"><summary>{t.s164}{" "}<span aria-hidden="true">+</span></summary><div className="episode-background-grid"><div><h3>{t.s165}</h3><p>{t.s166}</p></div><div><h3>{t.s167}</h3><p>{t.s168}</p></div><div><h3>{t.s169}</h3><p>{t.s170}</p></div></div></details>
  <div className="comic-footnote"><p>{t.s171}</p><div><a href="https://eposmanas.ru/prozaicheskyi%20variant%20epos%20manas/-159/67250877.html" target="_blank" rel="noopener noreferrer">{t.s172}</a><br /><a href="https://eposmanas.ru/prozaicheskyi%20variant%20epos%20manas/-159/26664801.html" target="_blank" rel="noopener noreferrer">{t.s173}</a></div></div>
  <a className="text-link" href="#legacy">{t.s174}{" "}<span aria-hidden="true">↗</span></a>
 </div>
    </section>
    <section className="chapter" id="legacy" aria-labelledby="legacy-title"><div className="container"><div className="section-heading reveal"><div><div className="chapter-top"><span className="chapter-number">07</span><span className="rule"></span><span className="eyebrow">{t.s175}</span></div><h2 id="legacy-title">{t.s176}<br /><em>{t.s177}</em></h2></div><div><p className="kyrgyz-title" lang="ky">Мурас</p><p className="section-intro">{t.s178}</p></div></div><div className="legacy-grid reveal"><article className="generation"><span className="generation-id">{t.s179}</span><div className="generation-portrait generation-manas"><img src="/manas/hero-manas.webp" width="1983" height="793" alt={t.s180} loading="lazy" decoding="async"/></div><h3>{t.s181}</h3><span className="generation-kyrgyz" lang="ky">Манас</span><p>{t.s182}</p><span className="generation-motto">{t.s183}</span></article><article className="generation"><span className="generation-id">{t.s184}</span><div className="generation-portrait"><img src="/manas/semetey.webp" width="1122" height="1402" alt={t.s185} loading="lazy" decoding="async"/></div><h3>{t.s186}</h3><span className="generation-kyrgyz" lang="ky">Семетей</span><p>{t.s187}</p><span className="generation-motto">{t.s188}</span></article><article className="generation"><span className="generation-id">{t.s189}</span><div className="generation-portrait"><img src="/manas/seytek.webp" width="1122" height="1402" alt={t.s190} loading="lazy" decoding="async"/></div><h3>{t.s191}</h3><span className="generation-kyrgyz" lang="ky">Сейтек</span><p>{t.s192}</p><span className="generation-motto">{t.s193}</span></article></div></div></section>
    <div className="ornament-divider" aria-hidden="true"><svg><use href="#shyrdak"/></svg></div>
    <section className="chapter voice" id="voice" aria-labelledby="voice-title"><div className="container voice-layout"><figure className="voice-image reveal" style={{ "margin": "0" }}><img src="/manas/manaschi.jpg" width="1024" height="1024" alt={t.s194} loading="lazy" decoding="async"/><figcaption className="art-caption"><span>{t.s195}</span><span>{t.s196}</span></figcaption></figure><div className="reveal"><div className="chapter-top"><span className="chapter-number">08</span><span className="rule"></span><span className="eyebrow">{t.s197}</span></div><h2 id="voice-title">{t.s198}<br /><em>{t.s199}</em></h2><p className="kyrgyz-title" lang="ky">Манасчылар</p><div className="prose"><p>{t.s200}</p><p>{t.s201}</p></div><div className="audio-box"><button className="play-button" id="listen" aria-label={t.s202} aria-haspopup="dialog"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 4l14 8-14 8z"/></svg></button><div className="audio-info"><div className="audio-title">{t.s203}</div><div className="audio-credit">{t.s204}</div></div><div className="waveform" aria-hidden="true"></div></div><p className="listen-note">{t.s205}<br />{t.s206}</p></div></div></section>
    <section className="closing" aria-label={t.s207}><svg className="closing-symbol" viewBox="0 0 140 140" aria-hidden="true"><g className="closing-rays"><g mask="url(#emblem-rays-mask)"><use href="#tunduk" width="140" height="140"/></g></g><g clipPath="url(#emblem-center-clip)"><use href="#tunduk" width="140" height="140"/></g><circle cx="70" cy="70" r="42.3" fill="none" stroke="currentColor" strokeWidth=".7"/></svg><h2>{t.s208}{" "}<em>{t.s209}</em></h2><p lang="ky">Кырк уруу. Бир эл. Түбөлүк мурас.</p></section>
    </div>
    <footer className="footer"><div className="container"><div className="footer-top"><a className="footer-brand" href="#">МАНАС</a><span className="footer-tag">{t.s210}</span><div className="footer-links"><a href="#sources" id="sources-link">{t.s211}</a><a href="#">{t.s212}</a></div></div><details className="credits" id="sources"><summary>{t.s213}</summary><p>{t.s214}</p><p>{t.s215}</p><p>{t.s216}{" "}<a href="https://ich.unesco.org/en/RL/kyrgyz-epic-trilogy-manas-semetey-seytek-00876" target="_blank" rel="noopener noreferrer">{t.s217}</a> · <a href="https://ich.unesco.org/en/RL/ala-kiyiz-and-shyrdak-art-of-kyrgyz-traditional-felt-carpet-making-00693" target="_blank" rel="noopener noreferrer">{t.s218}</a> · <a href="https://www.silkroadfoundation.org/folklore/manas/manasintro.html" target="_blank" rel="noopener noreferrer">{t.s219}</a> · <a href="https://en.unesco.org/silkroad/sites/default/files/knowledge-bank-article/vol_IVb%20silk%20road_oral%20tradition%20and%20the%20literary%20heritage.pdf" target="_blank" rel="noopener noreferrer">{t.s220}</a>.</p></details></div></footer>

    <aside className="chapter-current" id="chapter-current" aria-label={t.s221}>
 <button type="button" id="chapter-open" aria-label={t.s222} aria-haspopup="dialog" aria-controls="chapter-map"><span className="chapter-current-number" id="chapter-current-number">01</span><span className="chapter-current-label" id="chapter-current-label">{t.s021}</span><span aria-hidden="true">⊞</span></button>
 <a className="journey-next" href="#comrades" aria-label={t.s223}>→</a>
 <button type="button" className="motion-toggle" id="motion-toggle" data-motion-toggle aria-label={t.s224} aria-pressed="false"><svg className="motion-pause" viewBox="0 0 16 16" aria-hidden="true"><path d="M3 2h3v12H3zm7 0h3v12h-3z"/></svg><svg className="motion-play" viewBox="0 0 16 16" aria-hidden="true"><path d="M4 2l10 6-10 6z"/></svg><span className="motion-toggle-label">{t.s225}</span></button>
    </aside>
    <dialog className="dialog chapter-map" id="chapter-map" aria-labelledby="chapter-map-title"><button type="button" className="dialog-close" aria-label={t.s226}>×</button><span className="eyebrow red">{t.s227}</span><h2 id="chapter-map-title">{t.s228}<br />{t.s229}</h2><nav className="chapter-map-links" aria-label={t.s230}>
 <a href="#origin"><span>01</span><span><strong>{t.s021}</strong><small lang="ky">Жаралуу</small></span><span aria-hidden="true">↗</span></a>
 <a href="#comrades"><span>02</span><span><strong>{t.s031}</strong><small lang="ky">Кырк Чоро</small></span><span aria-hidden="true">↗</span></a>
 <a href="#battles"><span>03</span><span><strong>{t.s057}</strong><small lang="ky">Согуштар</small></span><span aria-hidden="true">↗</span></a>
 <a href="#episode"><span>04</span><span><strong>{t.s231}</strong><small lang="ky">Көкөтөйдүн ашы</small></span><span aria-hidden="true">↗</span></a>
 <a href="#koshoy"><span>05</span><span><strong>{t.s232}</strong><small lang="ky">Кошой менен Жолой</small></span><span aria-hidden="true">↗</span></a>
 <a href="#flight"><span>06</span><span><strong>{t.s233}</strong><small lang="ky">Каныкейдин Букарга качышы</small></span><span aria-hidden="true">↗</span></a>
 <a href="#legacy"><span>07</span><span><strong>{t.s175}</strong><small lang="ky">Мурас</small></span><span aria-hidden="true">↗</span></a>
 <a href="#voice"><span>08</span><span><strong>{t.s197}</strong><small lang="ky">Манасчылар</small></span><span aria-hidden="true">↗</span></a>
 </nav><p className="chapter-map-note">{t.s234}</p></dialog>
    <dialog className="dialog" id="person-dialog" aria-labelledby="person-title"><button className="dialog-close" aria-label={t.s235}>×</button><img className="dialog-portrait" id="person-portrait" alt="" width="1122" height="1402"/><svg className="dialog-symbol" aria-hidden="true"><use href="#horn"/></svg><div className="eyebrow red" id="person-role"></div><h2 id="person-title" style={{ "marginTop": "14px" }}></h2><p id="person-story"></p><span className="eyebrow red" id="person-kyrgyz" lang="ky"></span></dialog>
    <dialog className="dialog comic-reader" id="comic-dialog" aria-labelledby="comic-reader-title">
 <header className="comic-reader-header"><div><span className="eyebrow red" id="comic-reader-episode">{t.s236}</span><div className="comic-reader-counter" id="comic-reader-counter">{t.s237}</div></div><button type="button" className="dialog-close" aria-label={t.s238} autoFocus>×</button></header>
 <div className="comic-reader-body">
  <figure className="comic-reader-art"><img id="comic-reader-image" alt=""/><figcaption id="comic-reader-caption"></figcaption><p className="comic-swipe-hint">{t.s239}</p></figure>
  <article className="comic-reader-story"><span className="eyebrow red" id="comic-reader-kicker"></span><h2 id="comic-reader-title"></h2><div id="comic-reader-text"></div><div className="comic-reader-detail"><h3>{t.s240}</h3><p id="comic-reader-detail"></p></div><a className="comic-reader-source" href="https://slaviccenter.osu.edu/news/daniel-prior-visits-osu-reading-memorial-feast-kokotoy-khan" target="_blank" rel="noopener noreferrer">{t.s241}</a></article>
 </div>
 <footer className="comic-reader-controls"><button type="button" id="comic-prev" aria-label={t.s242}>← <span>{t.s243}</span></button><div className="comic-reader-pages" role="group" aria-label={t.s244}><button type="button" data-comic-page="0" aria-label={t.s245}>01</button><button type="button" data-comic-page="1" aria-label={t.s246}>02</button><button type="button" data-comic-page="2" aria-label={t.s247}>03</button><button type="button" data-comic-page="3" aria-label={t.s248}>04</button></div><button type="button" id="comic-next" aria-label={t.s249}><span>{t.s250}</span> →</button></footer>
 <span className="sr-only" id="comic-reader-status" role="status" aria-live="polite" aria-atomic="true"></span>
    </dialog>
    <dialog className="dialog video-dialog" id="video-dialog" aria-labelledby="video-title"><button className="dialog-close" aria-label={t.s251}>×</button><h2 id="video-title">{t.s252}</h2><div className="video-frame" id="video-frame"></div><p>{t.s253}{" "}<a href="https://www.youtube.com/watch?v=5C5OZC7kXo4" target="_blank" rel="noopener noreferrer">{t.s254}</a>.</p></dialog>

  </>;
}
