export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { Space_Grotesk, Advent_Pro, Jura } from 'next/font/google'
const font = Jura({weight: ['300','400','500','600','700'],style: 'normal', subsets: ['latin'], display: 'swap' })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru" className={font.className}>
      <head>
        <link rel="shortcut icon" href="/favicon.png" sizes="any" />
        <title>Создание Сайтов в Бишкеке</title>
      </head>
      {children}
    </html>
  )
}
