import type { Locale } from '@/lib/i18n.config'

type ContactCopy = { intro: string; close: string; name: string; email: string; phone: string; subject: string; message: string; send: string; hint: string; optional: string }
export const contactCopy: Record<Locale, ContactCopy> = {
  en: { intro: 'Tell us where you want to go. We’ll help you shape the journey.', close: 'Close contact window', name: 'Your name', email: 'Your email', phone: 'Phone number', subject: 'Subject', message: 'Tell us about your trip', send: 'Open email draft', hint: 'Your email app will open with your message. Review it there before sending.', optional: 'optional' },
  fr: { intro: 'Dites-nous où vous rêvez d’aller. Nous vous aiderons à préparer le voyage.', close: 'Fermer la fenêtre de contact', name: 'Votre nom', email: 'Votre e-mail', phone: 'Téléphone', subject: 'Objet', message: 'Parlez-nous de votre voyage', send: 'Préparer un e-mail', hint: 'Votre application e-mail s’ouvrira avec votre message. Vérifiez-le avant de l’envoyer.', optional: 'facultatif' },
  de: { intro: 'Wohin möchten Sie reisen? Wir helfen Ihnen bei der Planung.', close: 'Kontaktfenster schließen', name: 'Ihr Name', email: 'Ihre E-Mail', phone: 'Telefonnummer', subject: 'Betreff', message: 'Erzählen Sie uns von Ihrer Reise', send: 'E-Mail-Entwurf öffnen', hint: 'Ihre E-Mail-App öffnet sich mit Ihrer Nachricht. Prüfen Sie diese vor dem Senden.', optional: 'optional' },
  es: { intro: 'Cuéntanos adónde quieres ir. Te ayudaremos a preparar el viaje.', close: 'Cerrar ventana de contacto', name: 'Tu nombre', email: 'Tu correo electrónico', phone: 'Teléfono', subject: 'Asunto', message: 'Cuéntanos sobre tu viaje', send: 'Preparar correo', hint: 'Tu aplicación de correo se abrirá con el mensaje. Revísalo antes de enviarlo.', optional: 'opcional' },
  it: { intro: 'Raccontaci dove vuoi andare. Ti aiuteremo a organizzare il viaggio.', close: 'Chiudi la finestra di contatto', name: 'Il tuo nome', email: 'La tua e-mail', phone: 'Telefono', subject: 'Oggetto', message: 'Raccontaci del tuo viaggio', send: 'Apri bozza e-mail', hint: 'La tua app e-mail si aprirà con il messaggio. Controllalo prima di inviarlo.', optional: 'facoltativo' },
  ru: { intro: 'Расскажите, куда хотите отправиться. Мы поможем спланировать путешествие.', close: 'Закрыть окно связи', name: 'Ваше имя', email: 'Ваша почта', phone: 'Телефон', subject: 'Тема', message: 'Расскажите о вашей поездке', send: 'Открыть черновик письма', hint: 'Сообщение откроется в вашем почтовом приложении. Проверьте его перед отправкой.', optional: 'необязательно' },
  ae: { intro: 'أخبرنا إلى أين تريد الذهاب. سنساعدك في التخطيط لرحلتك.', close: 'إغلاق نافذة التواصل', name: 'اسمك', email: 'بريدك الإلكتروني', phone: 'رقم الهاتف', subject: 'الموضوع', message: 'أخبرنا عن رحلتك', send: 'فتح مسودة البريد', hint: 'سيفتح تطبيق البريد رسالتك. راجعها هناك قبل إرسالها.', optional: 'اختياري' },
  cn: { intro: '告诉我们你想去哪里，我们将帮你规划旅程。', close: '关闭联系窗口', name: '你的姓名', email: '你的邮箱', phone: '电话号码', subject: '主题', message: '告诉我们你的旅行计划', send: '打开邮件草稿', hint: '邮件应用将打开你的消息。请在发送前检查内容。', optional: '选填' },
  jp: { intro: '行きたい場所を教えてください。旅の計画をお手伝いします。', close: 'お問い合わせを閉じる', name: 'お名前', email: 'メールアドレス', phone: '電話番号', subject: '件名', message: 'ご旅行について教えてください', send: 'メールの下書きを開く', hint: 'メールアプリにメッセージが表示されます。内容を確認してから送信してください。', optional: '任意' },
  kr: { intro: '가고 싶은 곳을 알려주세요. 여행 계획을 함께 세워드릴게요.', close: '문의 창 닫기', name: '이름', email: '이메일', phone: '전화번호', subject: '제목', message: '여행 계획을 알려주세요', send: '이메일 초안 열기', hint: '이메일 앱에서 메시지가 열립니다. 내용을 확인한 후 전송해 주세요.', optional: '선택' },
}
